In [1]:
import sys
sys.path.append('/Users/mariana/Documents/projects/ts/nanoTempoPFN')

from src.model.robust_scaler import RobustScaler

In [2]:
import jax.numpy as jnp
import jax

x = jnp.array(
    [[[[1.0], [10.0]],
      [[2.0], [20.0]],
      [[3.0], [30.0]],
      [[4.0], [40.0]],
    ]]
)

In [3]:
x.shape

(1, 4, 2, 1)

In [4]:
scaler = RobustScaler(epsilon=1e-7, min_scale=1e-3)

In [11]:
params = scaler.init(jax.random.PRNGKey(1), x)
preds, (m, iqr) = scaler.apply(params, x, (m, iqr))

In [12]:
preds

Array([[[[-0.99999994],
         [-1.        ]],

        [[-0.3333333 ],
         [-0.33333334]],

        [[ 0.3333333 ],
         [ 0.33333334]],

        [[ 0.99999994],
         [ 1.        ]]]], dtype=float32)

In [13]:
m

Array([[[[ 2.5],
         [25. ]]]], dtype=float32)

In [14]:
iqr

Array([[[[ 1.5],
         [15. ]]]], dtype=float32)