In [1]:
import sys
sys.path.append('/Users/mariana/Documents/projects/ts/nanoTempoPFN')

from src.model.robust_scaler import RobustScaler

In [2]:
import jax.numpy as jnp
import jax

x = jnp.array(
    [[[[1.0], [10.0]],
      [[2.0], [20.0]],
      [[3.0], [30.0]],
      [[4.0], [40.0]],
    ]]
)

In [3]:
x.shape

(1, 4, 2, 1)

In [4]:
scaler = RobustScaler(epsilon=1e-7, min_scale=1e-3)

In [11]:
params = scaler.init(jax.random.PRNGKey(1), x)
preds, (m, iqr) = scaler.apply(params, x, (m, iqr))

In [12]:
preds

Array([[[[-0.99999994],
         [-1.        ]],

        [[-0.3333333 ],
         [-0.33333334]],

        [[ 0.3333333 ],
         [ 0.33333334]],

        [[ 0.99999994],
         [ 1.        ]]]], dtype=float32)

In [13]:
m

Array([[[[ 2.5],
         [25. ]]]], dtype=float32)

In [14]:
iqr

Array([[[[ 1.5],
         [15. ]]]], dtype=float32)

In [2]:
import random
import numpy as np

random.choices(np.array([1, 2, 3]), weights=np.array([1, 1, 100]))

[np.int64(3)]

In [21]:
GIFT_EVAL_FORECAST_LENGTHS = {
    48: 5,
    720: 38,
    480: 38,
    30: 3,
    300: 16,
    8: 2,
    120: 3,
    450: 8,
    80: 8,
    12: 2,
    900: 10,
    180: 3,
    600: 10,
    60: 3,
    210: 3,
    195: 3,
    140: 3,
    130: 3,
    14: 1,
    18: 1,
    13: 1,
    6: 1,
}

def sample_future_length():
    return random.choices(list(GIFT_EVAL_FORECAST_LENGTHS.keys()), weights=list(GIFT_EVAL_FORECAST_LENGTHS.values()))

In [22]:
sample_future_length()

[140]